steps:
- name: 'docker.io/library/python:3.7'
  id: Environment
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install -r requirements.txt'
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy
  entrypoint: bash
  args: [ '-c', 'if [ "$BRANCH_NAME" == "main" ]; then echo "$BRANCH_NAME" && gsutil -m rsync -d -r ./dags gs://${_COMPOSER_BUCKET}/dags; else echo "Working on $BRANCH_NAME"; fi']
substitutions:
    _COMPOSER_BUCKET: asia-northeast2-airflow-af25a695-bucket
